---
applications:
- name: fortuneService
  buildpacks:
   - dotnet_core_buildpack
  memory: 256M
  disk_quota: 200M
  command: cd ${HOME} && ./Fortune-Teller-Service
  env:
    ASPNETCORE_ENVIRONMENT: Development
  services:
   - myDiscoveryService
