---
applications:
- name: fortuneui
  buildpacks:
   - hwc_buildpack
  memory: 256M
  disk_quota: 200M
  stack: windows
  command: .\Fortune-Teller-UI
  env:
    ASPNETCORE_ENVIRONMENT: Development
  services:
   - myDiscoveryService
