AppSettings:
  SiteTitle: Music Store
  CacheDbResults: true
Logging:
  IncludeScopes: false
  LogLevel:
    Default: Debug
    System: Warning
    Microsoft: Warning
eureka:
  client:
    serviceUrl: http://eurekaserver:8761/eureka/
    validateCertificates: false
sqlserver:
  credentials:
    server: sqlserver
    username: sa
    password: SteeltoeR0cks
management:
  endpoints:
    cloudfoundry:
      validateCertificates: false
