eureka:
  client:
    shouldRegisterWithEureka: false
mysql:
  client:
    database: steeltoe2
    username: root
    password: steeltoe
sqlserver:
  credentials:
    database: MusicStore
DefaultAdminUsername: Administrator@test.com
DefaultAdminPassword: YouShouldChangeThisPassword1!
