eureka:
  client:
    shouldFetchRegistry: false
  instance:
    port: 5000
mysql:
  client:
    database: steeltoe
    username: root
    password: steeltoe
sqlserver:
  credentials:
    database: MusicService
