eureka:
  client:
    shouldFetchRegistry: false
  instance:
    port: 6000
mysql:
  client:
    database: steeltoe1
    username: root
    password: steeltoe
sqlserver:
  credentials:
    database: ShoppingCart
