trigger:
  branches:
    include:
      - master
  paths:
    include:
      - config/*
      - Management/src/CloudFoundry/*

# skip pipeline for PRs
pr: none

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Management
      sample: CloudFoundry
