trigger:
  branches:
    include:
      - master
  paths:
    include:
      - config/*
      - Connectors/src/PostgreEFCore/*

# skip pipeline for PRs
pr: none

variables:
  - group: 'PCFone Credentials'

jobs:
  - template: templates/cloud-foundry-job.yaml
    parameters:
      feature: Connectors
      sample: PostgreEFCore
